// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MultiTenants.Tenant.Model;
using System;

namespace MultiTenants.Migrations
{
    [DbContext(typeof(TenantCatalogDbContext))]
    [Migration("20171228074853_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("MultiTenants.Tenant.Model.AppTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConnectionString");

                    b.Property<string>("HostName");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("AppTenants");
                });
#pragma warning restore 612, 618
        }
    }
}
